export const CatConfig = {
    name: 'Milo',
    walkSpeed: 1.8,
    turnSpeed: 3.0,
    idleDuration: { min: 2, max: 5 },
    walkDuration: { min: 3, max: 7 },
    sitDuration: { min: 3, max: 8 },
    sleepDuration: { min: 8, max: 15 },
    affectionGain: 1.2,
    happinessGain: 1.0,
    energyDrain: 0.5,
    energyRegen: 2.0,
    appearance: {
        furColor: 0xD98943,
        bellyColor: 0xF5D5A0,
        eyeColor: 0x4F9C52,
        noseColor: 0xFF8FAB,
    },
    personality: {
        friendliness: 0.8,
        curiosity: 0.7,
        energy: 0.6,
        playfulness: 0.9,
        independence: 0.5,
    },
    stats: {
        affection: 50,
        happiness: 70,
        energy: 80,
        hunger: 20,
    },
    behaviors: [
        { action: 'walk',    weight: 35 },
        { action: 'idle',    weight: 25 },
        { action: 'sit',     weight: 20 },
        { action: 'explore', weight: 12 },
        { action: 'sleep',   weight: 8  },
    ],
    interestPoints: [
        { id: 'pond',      position: { x: 5,  z: -5  } },
        { id: 'bench',     position: { x: -6, z: 2   } },
        { id: 'cathouse',  position: { x: 6,  z: 5   } },
        { id: 'flowers',   position: { x: -4, z: -4  } },
        { id: 'center',    position: { x: 0,  z: 0   } },
    ],
};
